### ISSUE TITLE
ngrok is not yet ready to start tunnels

### ISSUE THREAD

**Issue by w3nda** [screener-io/screener-storybook#98] opened 2019-09-15 12:43 UTC
Environment:

- Chrome latest on Mac
- screener-storybook v0.18.7 **and** v0.17.8

tried using both versions, but I end up with this message in my log:
![image](https://user-images.githubusercontent.com/12185681/64921734-7bfea980-d7cf-11e9-9018-8accef06642e.png)

it may be related to this issue: https://github.com/bubenshchykov/ngrok/issues/100
which was fixed in ngrok-v3

**Comment by loyalchow** [comment] 2019-09-16 03:52
@w3nda ngrok made a change a few months ago which caused this error message to be outputted. This should be handled in v0.18.7, which automatically tries to re-connect to ngrok on error. The actual change is in screener-runner v0.10.40+, which the latest screener-storybook is pinned to.  Do you see this message outputted multiple times? Do you have the latest version of screener-runner?

Also, which version of ngrok are you running? You can see this by going to `node_modules/screener-ngrok/bin` and running `./ngrok version`

Since the update we have not seen this issue, except in cases when a client's VPN network blocked access to ngrok.

**Comment by w3nda** [comment] 2019-09-16 07:21
ngrok version 2.3.34

**Comment by loyalchow** [comment] 2019-09-16 20:46
@w3nda we have tried to reproduce with latest versions of screener-storybook, screener-runner, and Ngrok 2.3.34 - but we have not been able to reproduce the issue/error.

When going into `node_modules/screener-ngrok/bin`, can you run `./ngrok http 3000`? This will attempt to create a tunnel directly using the ngrok client.

We have also opened a ticket with the Ngrok team

**Comment by w3nda** [comment] 2019-09-18 06:29
@loyalchow yes, it works fine the tunnel is up.

**Comment by loyalchow** [comment] 2019-09-18 21:18
@w3nda Ok, so you're able to connect to ngrok directly, but not when running through screener. Does this error output every time consistently, or is this intermittent?

I'm assuming screener-storybook has worked for you before, and this issue is new, is that correct?
If this issue is consistent, and screener has worked for you previously without this issue, can you try rollback to a previous version of ngrok client? Here's command line to do so:

```
NGROK_IGNORE_CACHE=true NGROK_CDN_PATH="/a/2eQSxoyZAyH/ngrok-2.3.30-" node ./node_modules/screener-ngrok/postinstall.js
```

**Comment by loyalchow** [comment] 2019-10-04 20:21
Closing issue. Heard this has been resolved on the client's end, and they are no longer seeing issues

**Closed by loyalchow** 2019-10-04 20:21 UTC
